# 1.k: v
# 2.application.properties 优先
# 3.左侧对其就是同一层级

server:
  port: 8888

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    name: root
    password: 959452



---
# 配置复杂对象
person:
  name: aaaaa
  age: 33
  birth-day: 1010/11/12 12:12:12
  like: true
  child:
    name: bbbbb
    age: 44
    birth-day: 1078/11/23
  # text: ["abc", "def"]
    text:
      - abc
      - def
      - |   # 大文本，怎么输入就怎么输出 person.getChild().getText().get(3)
        11111111111111111
        22222222222222222
        33333333333333333
        44444444444444444
        55555555555555555
        66666666666666666
      - > # 大文本，会压缩换行符号为空格
        11111111111111111
        22222222222222222
        33333333333333333
        44444444444444444
        55555555555555555
        66666666666666666
  dogs:
    - name: ccccc
      age: 3
    - name: ddddd
      age: 4
  cats:
    c1:
      name: eeeee
      age: 1
    c2: {name: fffff, age: 2}







